### ISSUE TITLE
Need to implement few methods of simple interface

### ISSUE THREAD

**Issue by seokirill** [seokirill/AsyncStorage#1]
**Interface:**
https://github.com/seokirill/AsyncStorage/blob/master/src/js/interface/AsyncStorage.js

- [x] setItem()
- [x] getItem()

**Comment by nelo112** [comment]
Could you give an example, of how you want to use these functions?

**Comment by seokirill** [comment]
The same as AsyncStorage in ReactNative
https://facebook.github.io/react-native/docs/asyncstorage.html

**Comment by nelo112** [comment]
Hi, are you sure the getItem is correct?
Use case:
I call the getItem before setItem. I would expect my getItem promise to resolve once the value is set. With your current ´code you get a immediately resolving promise that returns "undefined".
Current:
`getItem('foobar').then( (value) => console.log(value)) // prints 'undefined' immediately`

Expected:
`getItem('foobar').then( (value) => console.log(value)) // doesn't print anything yet`
`setItem('foobar', 'hello world') //now 'hello world' is printed`

Is my expectation wrong?

**Comment by seokirill** [comment]
He there!

I think that u wrong, because it is Asycnhronus storage with `Promises`.

See some docs:
https://facebook.github.io/react-native/docs/asyncstorage.html

Are u use `Promises` before?

**Comment by seokirill** [comment]
```javascript
setItem('foobar', '11111')
getItem('foobar').then( (value) => console.log(value)) 
setItem('foobar', '22222')
```

Which text that code should print in your logik?

**Comment by nelo112** [comment]
'111111'
because I'd assume 'getItem' returns the first available valid value.

Yes, I've worked with promises before.

With the current implementation you have to ask yourself "What do the promises actually do?"
Since all the promises are immediately resolved with the current value the promise don't fullfill their purpose (that being "waiting for the data to be available").

**Comment by seokirill** [comment]
Okay, lets try how it works in ReactNative.

It is implementation of ReactNative AsyncStorage for more isomorphic code.

**Comment by seokirill** [comment]
<img width="902" alt="2016-10-25 15 17 01" src="https://cloud.githubusercontent.com/assets/11396467/19685633/426617ce-9ac6-11e6-9915-f1c9fabaa819.png">
<img width="727" alt="2016-10-25 15 17 13" src="https://cloud.githubusercontent.com/assets/11396467/19685637/47ea47b0-9ac6-11e6-850b-0e309fda8f5a.png">

**Comment by nelo112** [comment]
Alright. The documentation isn't 100% clear, but this was just the way I expected it do work. 
Still not sure how the storage is async if all promises are instantly resolved or what the purpose is, but that's another discussion :D

**Comment by seokirill** [comment]
Mechanism which take some data from "databse" is asynchronus = non blocked.

So if its so slow, next code lines will not blocked and interface will look like high-perfomance thing (:
